module.exports = [
  { name: 'Algeciras', code: 'ESALG', country: 'Spain' },
  { name: 'Apapa', code: 'NGAPP', country: 'Nigeria' },
  { name: 'Bahrain', code: 'BHKBS', country: 'Bahrain' },
  { name: 'Buenos Aires', code: 'ARBUE', country: 'Argentina' },
  { name: 'Gothenburg', code: 'SEGOT', country: 'Sweden' },
  { name: 'Itajaí', code: 'BRITJ', country: 'Brazil' },
  { name: 'Lázaro Cárdenas', code: 'MXLZC', country: 'Mexico' },
  { name: 'Los Angeles', code: 'USLAX', country: 'USA' },
  { name: 'Maasvlakte II, Rotterdam', code: 'NLMSV', country: 'Rotterdam' },
  { name: 'Medport Tangier', code: 'MATNG', country: 'Morocco' },
  { name: 'Monrovia', code: 'LRMLW', country: 'Liberia' },
  { name: 'Mobile', code: 'USMOB', country: 'USA' },
  { name: 'Moin', code: 'CRPMN', country: 'Costa Rica' },
  { name: 'Onne', code: 'NGONN', country: 'Nigeria' },
  { name: 'Port Elizabeth', code: 'USNWK', country: 'USA' },
  { name: 'Suez Canal Container Terminals - SCCT', code: 'EGPSD', country: 'Egypt' },
  { name: 'South Florida Container Terminal, Miami', code: 'USMIA', country: 'USA' },
  { name: 'Tangier', code: 'MAPTM', country: 'Morocco' },
  { name: 'Vado', code: 'ITVDL', country: 'Italy' },
  { name: 'Valencia', code: 'ESVLC', country: 'Spain' },
  { name: 'Yucatán', code: 'MXPGO', country: 'Mexico' },
];
